site_name: MsgPHP Documentation
site_description: Message based domain layers. Shipped with industry standard infrastructure.
repo_url: https://github.com/msgphp/msgphp
edit_uri: blob/master/docs/
site_dir: var/docs/build/

theme:
    name: material
    custom_dir: docs/.theme
extra_css: [style.css]

markdown_extensions:
    - codehilite

pages:
- Home: index.md
- Code Conventions: code-conventions.md
- Domain-Driven-Design:
    - Identifiers: ddd/identifiers.md
    - Identities: ddd/identities.md
    - Identity mapping: ddd/identity-mapping.md
    - Collections: ddd/collections.md
    - Factories:
        - Object Factory: ddd/factory/object.md
        - Entity Aware Factory: ddd/factory/entity-aware.md
        - Static Factory: ddd/factory/static.md
    - Repositories: ddd/repositories.md
    - Entities: ddd/entities.md
- Event-Sourcing:
    - Events: event-sourcing/events.md
    - Event handlers: event-sourcing/event-handlers.md
- Message Driven:
    - Message Bus: message-driven/message-bus.md
    - Message Dispatcher: message-driven/message-dispatcher.md
    - CQRS: message-driven/cqrs.md
- Projection:
    - Models: projection/models.md
    - Documents: projection/documents.md
    - Document Transformers: projection/document-transformers.md
    - Type Registry: projection/type-registry.md
    - Repositories: projection/repositories.md
    - Synchronization: projection/synchronization.md
- Infrastructure:
    - API Platform: infrastructure/api-platform.md
    - Doctrine Collections: infrastructure/doctrine-collections.md
    - Doctrine DBAL: infrastructure/doctrine-dbal.md
    - Doctrine ORM: infrastructure/doctrine-orm.md
    - Elasticsearch: infrastructure/elasticsearch.md
    - PSR Container: infrastructure/psr-container.md
    - Symfony Console: infrastructure/symfony-console.md
    - UUID: infrastructure/uuid.md
- Cookbook:
    - Bundle Installation: cookbook/bundle-installation.md
- Reference:
    - Domain Identifiers: reference/identifiers.md
    - Domain Entities: reference/entities.md
    - Doctrine Identifier Types: reference/doctrine-identifier-types.md
