site_name: MsgPHP Documentation
site_description: Message based domain layers. Shipped with industry standard infrastructure.
repo_url: https://github.com/msgphp/msgphp
edit_uri: blob/master/docs/
site_dir: var/docs/build/

theme:
    name: 'material'
extra_css: [style.css]
markdown_extensions:
    - codehilite

pages:
- Home: index.md
- Code conventions: code-conventions.md
- Domain-driven-design:
    - Identifiers: ddd/identifiers.md
    - Identity mapping: ddd/identity-mapping.md
    - Collections: ddd/collections.md
    - Factories:
        - Object factory: ddd/factory/object.md
        - Entity factory: ddd/factory/entity.md
        - Static factory: ddd/factory/static.md
    - Repositories: ddd/repositories.md
    - Entities: ddd/entities.md
- Event sourcing:
    - Domain events: event-sourcing/domain-events.md
    - Domain event handlers: event-sourcing/domain-event-handlers.md
- Message driven:
    - Domain message bus: message-driven/domain-message-bus.md
    - CQRS: message-driven/cqrs.md
